### ISSUE TITLE
pwa-debug doesn't break for older version of node.js

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-pwa#133] opened 2019-12-03 12:01 UTC
testing https://github.com/microsoft/vscode/issues/85984:

- make sure to have a node manager like "nvm" installed
- install node version "8.11.4"
- use simple one liner program `console.log('hello world');`
- set breakpoint on first line
- use this launch config:
  ```js
  {
	"type": "pwa-node",
	"request": "launch",
	"name": "hello",
	"program": "${workspaceFolder}/hello.js",
	"runtimeVersion": "8.11.4"
  },
  ```

Observe:
program doesn't stop on first line.

Adding a "debugger;" statement doesn't help either.

If you change the type attribute from "pwa-node" to "node" it works fine.

**Comment by connor4312** [comment] 2019-12-03 16:01
This is probably a duplicate of https://github.com/microsoft/vscode-pwa/issues/79, which should be fixed in the today's build that runs at 8 AM PST.

**Comment by weinand** [comment] 2019-12-03 18:05
I'm not sure that this is a dup. Debugger statements should always be hit because they don't require a breakpoint from being registered.

**Comment by roblourens** [comment] 2019-12-03 18:09
vscode-pwa only supports slightly newer node versions, I think due to using the experimental 'inspector' module. Not sure what the minimum is, I think the latest 8.x should work. We need to figure that out and handle it...

**Comment by connor4312** [comment] 2019-12-03 18:22
May be https://github.com/microsoft/vscode-pwa/issues/134 then

**Comment by roblourens** [comment] 2019-12-03 18:26
Yeah I think it's covered by that

**Closed** 2019-12-03 18:26 UTC
Labels: duplicate
